### ISSUE TITLE
Temperature textfield not cleared when shorter text is displayed.

### ISSUE THREAD

**Issue by steadyjaw** [rackrick/MoonWatch#1]
Good day.
First of all. This thing is awesome! 
Well designed. Thank you for sharing this.

Just noticed a problem with text field in which the bed temperature ist displayed.
![IMG_20210521_201526](https://user-images.githubusercontent.com/36079537/119181384-d1459080-ba71-11eb-979b-eb3ee57893a6.jpg)
It shows the correct data, but it seems, there are still some artefacts visible from what what was shown a while ago. -> "100.0"

**Comment by rackrick** [comment]
Hey Martin,

thanks for the feedback and I'am happy you like it =)

Actually this is an known issue and already fixed and beeing tested right now. I still have a few things on my todo list which I want to implement into the project and wanted to release the fix along with a few other things. Unfortunately I am lacking time at the moment to develop own projects. Because of that I will just release the fix for this issue soon.

**Comment by rackrick** [comment]
here is the fix.
https://github.com/rackrick/MoonWatch/releases/tag/0.12-beta

**Comment by steadyjaw** [comment]
Awesome mate, will test fix soon and thanks for the quick response!
